### ISSUE TITLE
Release of the modified PointNet based model architecture?

### ISSUE THREAD

**Issue by jediofgever** [ibrahimhroob/lts_filter#9]
Hi @ibrahimhroob ,
Amazing work and thanks for the code. 

Is there the source code for the modified pointnet architecture? 
I am also trying to do a regression task on Pointcloud and your method could be a good reference for me to look to. 

Thank you!

**Comment by ibrahimhroob** [comment]
Hi Fetullah @jediofgever , 

Thank you, much appreciated. 

I will upload the training script and the modified network architecture later this week and will keep you posted. I do have two network versions, one based on PN++ and the other based on the point cloud transformer PCT. 

Thanks,

**Comment by jediofgever** [comment]
Thanks a lot @ibrahimhroob , looking forward to them!

**Comment by ibrahimhroob** [comment]
Hi @jediofgever , 

I added the network into [ecmr_23](https://github.com/ibrahimhroob/lts_filter/tree/ecmr_23) branch. 

Thanks

**Comment by jediofgever** [comment]
Great, will be checking it out. 

Many thanks
